config/routes.rb
ProductsClickpricecheckCom::Application.routes.draw do
  post 'categories/deleteall'=>'categories#deleteall'
  post 'categories/delete' => 'categories#delete'
  
  post 'categorytypes/deleteall'=>'categorytypes#deleteall'
  post 'categorytypes/delete' => 'categorytypes#delete'
  resources :categories
  resources :categorytypes
  
  controller :priority do
    get "priority/index"
    get "priority/delete"
    get "priority/new"
    get "priority/edit"
    post "priority/create"
    
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :parent,:class_name=>"Category",:foreign_key=>"category_id"
  belongs_to :categorytype,:foreign_key=>'categorytype_id'
  has_many :categories,:class_name=>"Category",:foreign_key=>"category_id"
  # def ParentCategories
      # Category.all
  # end
end

app/models/categorytype.rb
class Categorytype < ActiveRecord::Base
  has_many :categories
end

app/models/priority.rb
class Priority < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @page = params[:page]
    if params[:page].nil?
      @page = 1
    else
      if params[:page]==""
        @page = 1
      else
        @page = params[:page]
      end
    end
    if @mode!='search'
      @Categories = Category.all.paginate(:page => @page, :per_page => 10).includes(:categorytype,:parent)
    else
      @Categories=@Categories.paginate(:page=>@page,:per_page=>10).includes(:categorytype,:parent)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  def new
    @Category = Category.new
    @Categorytypes = Categorytype.all
    @ParentCategories = Category.all.includes(:categorytype,:parent)
    @mode= params[:mode]
    @page = params[:page]
  end  
  def create
    @mode= params[:mode]
    if params[:btnDelete]
        deleteall
        render "delete"
    elsif params[:btnSearch]
        @mode="search"
        search
        render "search"
    elsif params[:btnClear]
        @mode=""
        redirect_to action: 'index'
    else
      @Category = Category.new(category_params)
      @Category.save
      @page = params[:page]
      @Categories = Category.all.paginate(:page =>@page, :per_page => 10).includes(:categorytype,:parent)
      @ParentCategories = Category.all
      respond_to do |f|
         f.js 
      end
    end        
  end  
  def edit
    @Category = Category.find(params[:id])
    @Categorytypes = Categorytype.all
    @ParentCategories = Category.all
    @mode = params[:mode]
    render "new"
  end
  def update
    @Category = Category.find(params[:id])
    @mode= params[:mode]
    @Category.update(category_params)
    respond_to do |f|
      f.js {render "create"}
    end
  end
    
  
   private
  def category_params
    if :category.nil?
      params.permit(:id,:name,:categorytype_id,:category_id,:mode)
    else
      params.require(:category).permit(:id,:name,:categorytype_id,:category_id,:mode)
    end
  end
end

app/controllers/categorytypes_controller.rb
class CategorytypesController < ApplicationController
  def index
    @page = params[:page]
    if params[:page].nil? 
      @page = 1
    else 
      if params[:page]==""
        @page = 1
      else
        @page = params[:page]
      end
    end
    if @mode!='search'
      @Categorytypes = Categorytype.all.paginate(:page => @page, :per_page => 10)
    else
      @Categorytypes=@Categorytypes.paginate(:page=>@page,:per_page=>10)
    end
    respond_to do |format|
      format.html
      format.js
    end    
  end
  def edit
    @Categorytype = Categorytype.find(params[:id])
    @mode = params[:mode]
    render "new"
  end
  def update
    @Categorytype = Categorytype.find(params[:id])
    @mode= params[:mode]
    @Categorytype.update(categorytype_params)
    respond_to do |f|
      f.js {render "create"}
    end
  end
    
  def listtypes
    @Categorytypes = Categorytype.all
    render json: {:Result=>"OK",:Records=>@Categorytypes}
  end
  def new
    @Categorytype = Categorytype.new
    @mode= params[:mode]
    @page = params[:page]
  end
  def create
    @mode= params[:mode]
    if params[:btnDelete]
        deleteall
        render "delete"
    elsif params[:btnSearch]
        @mode="search"
        search
        render "search"
    elsif params[:btnClear]
        @mode=""
        redirect_to action: 'index'
    else
      @Categorytype = Categorytype.new(categorytype_params)
      @Categorytype.save
      @page = params[:page]
      @Categorytypes = Categorytype.all.paginate(:page =>@page, :per_page => 10)
      respond_to do |f|
         f.js 
      end
    end        
  end
  def deleteall
    @Cattypes= params[:ps] 
    @Cattypes.each { |f| 
      @Cattype = Categorytype.find(f)
      if (@Cattype)
      @Cattype.destroy
      end
     }
    @page = params[:page]
    @Categorytypes = Categorytype.all.paginate(:page =>@page, :per_page => 10)   
  end
  def delete
    @Cattype = Categorytype.find(params[:id])
    if (@Cattype)
      @Cattype.destroy
    end
    
    # @Cattypes= params[:ps] 
    # @Cattypes.each { |f| 
      # @Cattype = Categorytype.find(f)
      # if (@Cattype)
      # @Cattype.destroy
      # end
     # }
    @page = params[:page]
    @Categorytypes = Categorytype.all.paginate(:page =>@page, :per_page => 10)   
  end
  def search    
    if (!params[:txtName].nil? and params[:txtName]!='')
     
      @Categorytypes = Categorytype.where("name like ?",'%' + params[:txtName] + '%')
      @page = params[:page]
      @Categorytypes = @Categorytypes.paginate(:page=>1,:per_page=>@Categorytypes.count)
    else
      @Categorytypes = Categorytype.all.paginate(:page=>@page,:per_page=>@Categorytypes.count)
    end
  end
    
  private
  def categorytype_params
    if :categorytype.nil?
      params.permit(:id,:name,:mode)
    else
      params.require(:categorytype).permit(:id,:name,:mode)
    end
  end
end

app/controllers/priority_controller.rb
class PriorityController < ApplicationController
  def index
    @page = params[:page]
    if params[:page].nil? 
      @page = 1
    else 
      if params[:page]==""
        @page = 1
      else
        @page = params[:page]
      end
    end
    if @mode!='search'
      @priorities = Priority.all.paginate(:page => @page, :per_page => 10)
    else
      @priorities=@priorities.paginate(:page=>@page,:per_page=>10)
    end
    respond_to do |format|
      format.html
      format.js
    end       
  end
  def edit
    
  end
  def new
    @priority = Priority.new
    @mode= params[:mode]
    @page = params[:page]
  end
  def create
    @mode= params[:mode]
    if params[:btnDelete]
        deleteall
        render "delete"
    elsif params[:btnSearch]
        @mode="search"
        search
        render "search"
    elsif params[:btnClear]
        @mode=""
        redirect_to action: 'index'
    else
      @priority = Priority.new(priority_params)
      @priority.save
      @page = params[:page]
      @priorities = Priority.all.paginate(:page =>@page, :per_page => 10)
      respond_to do |f|
         f.js 
      end
    end        
  end
  
  private
  def priority_params
      params.require(:priority).permit(:id,:name,:mode)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorytypes_helper.rb
module CategorytypesHelper
end

app/helpers/priority_helper.rb
module PriorityHelper
end

app/views/categories/index.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Categories</title>
	<script>
			$(document).ready(function() 
			{			
					/* selecting the row */
					$('.dataTable input[type=checkbox]').click(function(event)
					{
						event.stopPropagation()
					});
					
					$(document).on('dblclick','.dataTable tbody tr',openEditWindow);
					$('.pagination a').attr('data-remote', 'true');
					$( "#dialog-form" ).dialog({
						dialogClass: "no-close",
				      autoOpen: false,
				      height: 300,
				      width: 500,
				      modal: true,
			    	});			 
				    $("#btnClose").click(closeWindow);
			 		$('.ui-dialog-buttonpane').find('button').css('visibility','hidden');					
					$("#btnNew").click(openNewWindow);
			});
			
			function closeWindow(id)
			{
				$('#'+id).addClass('normalRow');		  			
				$("#dialog-form").dialog("close");
			}
			function openEditWindow()
	  		{
	  			if ($('#'+this.id).hasClass('highlightRow')==false)
	  			$('#'+this.id).addClass('highlightRow');
	  			
	  			id = this.id.replace('r','');
	  			$( "#dialog-form" ).dialog( "open" );
			    $("#newdialog").attr('src','<%=categories_path%>/'+id+'/edit?mode=edit');
	  		}
	  		function openNewWindow()
	  		{
	  			  $( "#dialog-form" ).dialog( "open" );
		          page = $("#page").val();
				  $("#newdialog").attr('src','<%=new_category_url%>?mode=new&page='+page);
	  		}			
			//updating the data
			function updateData(mode,data,rowid)
			{
				if (mode=="new")
				{
					// $(".dataTable > tbody:last").append(data);
					$("#categories").html(data);
					$('.pagination a').attr('data-remote', 'true');
				}
				else
				{
					alert("edit");
					alert(data);
				$("#" + rowid).replaceWith(data);
				}

			}
			function selectRows()
			{
				var selected = $("#selectAll").prop("checked");
				if (selected)
					$("input:checkbox").prop("checked",true);
				else
					$("input:checkbox").prop("checked",false);
		
				
			}
			function deleteRow(id)
			{
				$('#'+'c' + id).prop("checked",true);
				bln = deleteRows();
				if (bln)
					$('#btnDelete').submit();
				else
					$('#'+'c' + id).prop("checked",false);
				
				
			}
	function deleteConfirm(event)
	{
		if (confirm('Are you sure?')==true)
		{
			return true;
		}		
		else
		{
			event.preventDefault();
			return false;
			
		}
	}
	function setMode(mode)
	{
		$('#mode').val(mode);
	}
	function clearAll()
	{
		$('#txtName').val('');
		$('#txtCreated').val('');
		$('#txtStatus').val('');
	}
	function deleteRows()
	{
		var n = $("input:checkbox:checked" ).not("#selectAll").length;
		if (n<=0)
		{
			alert('Please select the category type[s] to delete!');
			return false;
		}
		else
		{
			//alert(ids);
			if (confirm('Are you sure?')==true)
			{
				//$('#btnDelete').submit();
				return true;
			}		
			else
			{
				return false;
			}
		}
	}
	</script>
	</head>
	<body>
		<%= form_tag({:controller => 'categories',:action => "index"},:method=>:post, remote: true) do %>
		<section id="tbar">
			<input type="button" id="btnNew" value="New" onclick="setMode('new')">
			<!-- <%= button_to "Delete",{:controller=>'categorytypes',:action=>'deleteall'},:remote=>true,:data => { confirm: 'Reallly?'}%> -->
			<input type="submit" id="btnDelete" name="btnDelete" value="Delete" onclick="return deleteRows();">
			<input type="submit" id="btnSearch" name="btnSearch" value="Search" onclick="setMode('search');">
			<input type="submit" id="btnClear" name="btnClear" value="Clear" onclick="clearAll();">
			<input type="button" id="btnClose" value="Close" style='display:none;visibility: hidden'/>
			<input type="text" id="page" name="page" value="<%=@page%>" style='display: none;visibility: hidden;'/>
			<input type="text" id="mode" name="mode" value="<%=@mode%>" style='display: none;visibility: hidden'/>
		</section>
		<div id="categories">
			<%= render :partial => 'shared/category' %>
		</div>
		<!-- dialog start -->
		<div id="dialog-form" title="New category">
			<iframe id="newdialog" name="newdialog" seamless="seamless" frameborder="0" height="100%" width="100%" scrolling="no"> 
		    </iframe>
		</div>
		<% end %>
		<!-- new dialog end -->
	</body>
</html>

app/views/categories/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>New Category</title>
		<script type="text/javascript">
			  $(document).ready(function()
			  {
			  		$("#btnCancel").click(closeWindow);
			  });
			  function closeWindow()
			  {
			  		window.parent.closeWindow('r<%=@Category.id%>');
			  }
		</script>
	</head>
	<body style="margin-left:0;margin-top:0px">
		<!-- <section id="head">
			<header>
			<h1>Add New Type:</h1>
			</header> 
		</section> -->
		<section id="content">
			<%= form_for(@Category, remote: true) do |p| %>
			<%= p.text_field :name, :placeholder=>'Enter the category name', :size=> 50, :required=> true, :autofocus=>true %>
			<br>
			<% if @mode == "new" %>
			<%= collection_select("category","categorytype_id",@Categorytypes,:id,:name,{ :prompt=>'Select category type'},{:style=>"width: 394px;line-height:50px;",:required=>true})%>
			<% else %>
			<%= collection_select("category","categorytype_id",@Categorytypes,:id,:name,{:include_blank=>'Select category type', :selected=>@Category.categorytype.id},{:style=>"width: 394px;line-height:50px;",:required=>true})%>
			<% end %>
			<br>
			<div id="parentcategories">
				<% if @mode == "new" %>
				<%= collection_select("category","category_id",@ParentCategories,:id,:name,{ :prompt=>'Select parent'},{:style=>"width: 394px;line-height:50px;"})%>
				<% else %>
				<%= collection_select("category","category_id",@ParentCategories,:id,:name,{ :include_blank=>'Select parent',:selected=> @Category.parent.present? ? @Category.parent.id :  0},{:style=>"width: 394px;line-height:50px;"})%>
				<% end %>
			</div>
			<br>
			<br>
			<section id="tbar">
	        <%= hidden_field_tag "mode", @mode %>
	        <%= hidden_field_tag "page", @page %>
			<%= p.submit :id=>"btnSave", :value=>"Ok" %>
			<%= p.submit :id=>"btnCancel",:value=>"Cancel", :type=>"reset" %>
			</section>
			<% end %>
			<br>
			<br>
		</section>
	</body>
</html>

app/views/categorytypes/1searchOrdelete.js.erb
alert('i am ok illai');

app/views/categorytypes/backupcreate.js.erb
<% begin %>
	<% if @mode=="new"%>
		<% if (@Categorytype.new_record? == false) %>
			str = "";
			<% @Categorytypes.each do |c| %>
				str += "<tr> " + 
					   "<td><input type='checkbox' id='r<%=c.id%>' name='ps[]'/></td> " +
					   "<td><%=c.name %></td>";
				<% if !c.created_at.nil?  %>
					str = str + " <td><%=c.created_at.strftime('%Y-%m-%d')%></td> ";
				<% else %>
					str = str + " <td></td>";
				<% end %>			
								  
				<% if c.status.nil? %>
					str = str + " <td>Active</td> ";
				<% else %>
					str = str + " <td>Inactive</td>";
				<% end %>				  
				str = str + "<td><img src='assets/delete.png' /></td>";
				str = str + "</tr>";
			<% end %>
			<!-- alert(str); -->
			window.parent.updateData("new",str,"0");
			alert('<%=@Categorytype.name%> sucessfully created!');
			$("#categorytype_name").val("");
			$("#categorytype_name").focus();
		<% else %>
			alert('Error creating Category type');
		<%end%>		
	<% else %>
		window.parent.document.getElementById("btnClose").click();
	<% end %>
<% rescue Exception => e %>
	<% puts e.message %>
<% end %>

app/views/categorytypes/create.js.erb
<% begin %>
	<% if @mode=="new"%>
		<% if (@Categorytype.new_record? == false) %>
			window.parent.updateData("new","<%=escape_javascript(render(:partial => "shared/categorytype"))%>","0");
			$("#categorytype_name").val("");
			$("#categorytype_name").focus();
			<!-- alert('<%=@Categorytype.name%> sucessfully created!'); -->
		<% else %>
			alert('Error creating Category type');
		<%end%>		
	<% else %>
		str = " <tr id='r<%=@Categorytype.id%>'> " +
			  " <td><input type='checkbox' id='r<%=@Categorytype.id%>' name='ps[]'/></td> " +
			  " <td><%=@Categorytype.name %></td>  ";
			  <% if !@Categorytype.created_at.nil?  %>
				str += " <td><%=@Categorytype.created_at.strftime('%Y-%m-%d')%> </td>";
			  <% end %>
			  str += " 	</td> ";
			  <% if @Categorytype.status.nil? %>
				str += "<td>Active</td>";
			  <% else %>
				str += "<td>Inactive</td>";
			  <% end %>
			  str += "<td><img src='assets/delete.png' /></td>";
			  str += "</tr>";
			window.parent.updateData("edit",str,"r<%=@Categorytype.id%>");
			<!-- alert('<%=@Categorytype.name%> successfully updated!'); -->
			window.parent.closeWindow("r<%=@Categorytype.id%>");
			<!-- window.parent.document.getElementById("btnClose").click(); -->
	<% end %>
<% rescue Exception => e %>
	<% puts e.message %>
<% end %>

app/views/categorytypes/createold.js.erb
<% begin %>
	<% if @mode=="new"%>
		<% if (@Categorytype.new_record? == false) %>
			str = "<tr> " + 
				  "<td><input type='checkbox' id='r<%=@Categorytype.id%>' name='ps[]'/></td> " +
				  "<td><%=@Categorytype.name %></td>";
			<% if !@Categorytype.created_at.nil?  %>
				str = str + " <td><%=@Categorytype.created_at.strftime('%Y-%m-%d')%></td> ";
			<% else %>
				str = str + " <td></td>";
			<% end %>			
							  
			<% if @Categorytype.status.nil? %>
				str = str + " <td>Active</td> ";
			<% else %>
				str = str + " <td>Inactive</td>";
			<% end %>				  
			str = str + "<td><img src='assets/delete.png' /></td>";
			str = str + "</tr>";
			window.parent.updateData("new",str,"0");
			alert('<%=@Categorytype.name%> sucessfully created!');
			$("#categorytype_name").val("");
			$("#categorytype_name").focus();
		<% else %>
			alert('Error creating Category type');
		<%end%>		
	<% else %>
		window.parent.document.getElementById("btnClose").click();
	<% end %>
<% rescue Exception => e %>
	<% puts e.message %>
<% end %>

app/views/categorytypes/delete.js.erb
window.parent.updateData("new","<%=escape_javascript(render(:partial => "shared/categorytype"))%>","0");

app/views/categorytypes/index.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Category Types</title>
	<script>
			$(document).ready(function() 
			{			
					/* selecting the row */
					$('.dataTable input[type=checkbox]').click(function(event)
					{
						event.stopPropagation()
					});
					
					$(document).on('dblclick','.dataTable tbody tr',openEditWindow);
					$('.pagination a').attr('data-remote', 'true');
					$( "#dialog-form" ).dialog({
						dialogClass: "no-close",
				      autoOpen: false,
				      height: 300,
				      width: 500,
				      modal: true,
			    	});			 
				    $("#btnClose").click(closeWindow);
			 		$('.ui-dialog-buttonpane').find('button').css('visibility','hidden');					
					$("#btnNew").click(openNewWindow);
			});
			
			function closeWindow(id)
			{
				$('#'+id).addClass('normalRow');		  			
				$("#dialog-form").dialog("close");
			}
			function openEditWindow()
	  		{
	  			if ($('#'+this.id).hasClass('highlightRow')==false)
	  			$('#'+this.id).addClass('highlightRow');
	  			
	  			id = this.id.replace('r','');
	  			$( "#dialog-form" ).dialog( "open" );
			    $("#newdialog").attr('src','<%=categorytypes_path%>/'+id+'/edit?mode=edit');
	  		}
	  		function openNewWindow()
	  		{
	  			  $( "#dialog-form" ).dialog( "open" );
		          page = $("#page").val();
				  $("#newdialog").attr('src','<%=new_categorytype_url%>?mode=new&page='+page);
	  		}			
			//updating the data
			function updateData(mode,data,rowid)
			{
				if (mode=="new")
				{
					// $(".dataTable > tbody:last").append(data);
					$("#categorytypes").html(data);
					$('.pagination a').attr('data-remote', 'true');
				}
				else
				{
				$("#" + rowid).replaceWith(data);
				}

			}
			function selectRows()
			{
				var selected = $("#selectAll").prop("checked");
				if (selected)
					$("input:checkbox").prop("checked",true);
				else
					$("input:checkbox").prop("checked",false);
		
				
			}
			function deleteRow(id)
			{
				$('#'+'c' + id).prop("checked",true);
				bln = deleteRows();
				if (bln)
					$('#btnDelete').submit();
				else
					$('#'+'c' + id).prop("checked",false);
				
				
			}
	function deleteConfirm(event)
	{
		if (confirm('Are you sure?')==true)
		{
			return true;
		}		
		else
		{
			event.preventDefault();
			return false;
			
		}
	}
	function setMode(mode)
	{
		$('#mode').val(mode);
	}
	function clearAll()
	{
		$('#txtName').val('');
		$('#txtCreated').val('');
		$('#txtStatus').val('');
	}
	function deleteRows()
	{
		var n = $("input:checkbox:checked" ).not("#selectAll").length;
		if (n<=0)
		{
			alert('Please select the category type[s] to delete!');
			return false;
		}
		else
		{
			//alert(ids);
			if (confirm('Are you sure?')==true)
			{
				//$('#btnDelete').submit();
				return true;
			}		
			else
			{
				return false;
			}
		}
	}
	</script>
	</head>
	<body>
		<%= form_tag({:controller => 'categorytypes',:action => "index"},:method=>:post, remote: true) do %>
		<section id="tbar">
			<input type="button" id="btnNew" value="New" onclick="setMode('new')">
			<!-- <%= button_to "Delete",{:controller=>'categorytypes',:action=>'deleteall'},:remote=>true,:data => { confirm: 'Reallly?'}%> -->
			<input type="submit" id="btnDelete" name="btnDelete" value="Delete" onclick="return deleteRows();">
			<input type="submit" id="btnSearch" name="btnSearch" value="Search" onclick="setMode('search');">
			<input type="submit" id="btnClear" name="btnClear" value="Clear" onclick="clearAll();">
			<input type="button" id="btnClose" value="Close" style='display:none;visibility: hidden'/>
			<input type="text" id="page" name="page" value="<%=@page%>" style='display: none;visibility: hidden;'/>
			<input type="text" id="mode" name="mode" value="<%=@mode%>" style='display: none;visibility: hidden'/>
		</section>
		<div id="categorytypes">
			<%= render :partial => 'shared/categorytype' %>
		</div>
		<!-- dialog start -->
		<div id="dialog-form" title="New category type">
			<iframe id="newdialog" name="newdialog" seamless="seamless" frameborder="0" height="100%" width="100%" scrolling="no"> 
		    </iframe>
		</div>
		<% end %>
		<!-- new dialog end -->
	</body>
</html>

app/views/categorytypes/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>New Type</title>
		<script type="text/javascript">
			  $(document).ready(function()
			  {
			  		$("#btnCancel").click(closeWindow);
			  });
			  function closeWindow()
			  {
			  		window.parent.closeWindow('r<%=@Categorytype.id%>');
			  }
		</script>
	</head>
	<body style="margin-left:0;margin-top:0px">
		<!-- <section id="head">
			<header>
			<h1>Add New Type:</h1>
			</header> 
		</section> -->
		<section id="content">
			<%= form_for(@Categorytype, remote: true) do |p| %>
			<%= p.text_field :name, :placeholder=>'Enter the category type', :size=> 50, :required=> true, :autofocus=>true %>
			<br>
			<br>
			<section id="tbar">
	        <%= hidden_field_tag "mode", @mode %>
	        <%= hidden_field_tag "page", @page %>
			<%= p.submit :id=>"btnSave", :value=>"Ok" %>
			<%= p.submit :id=>"btnCancel",:value=>"Cancel", :type=>"reset" %>
			</section>
			<% end %>
			<br>
			<br>
		</section>
	</body>
</html>

app/views/categorytypes/search.js.erb
window.parent.updateData("new","<%=escape_javascript(render(:partial => "shared/categorytype"))%>","0");

app/views/categorytypes/show.html.erb
<b>welcome</b>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products.Clickpricecheck.Com</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/priority/create.js.erb
<% begin %>
	<% if @mode=="new"%>
		<% if (@Category.new_record? == false) %>	
			window.parent.updateData("new","<%=escape_javascript(render(:partial => "shared/category"))%>","0");
			<!-- $("#parentcategories").html("drop down"); -->
			$("#parentcategories").html("<%=escape_javascript(collection_select('category','category_id',@ParentCategories,:id,:name,{ :prompt=>'Select parent'},{:style=>'width: 394px;line-height:50px;'}))%>");
			$("#category_name").val("");
			$("#category_name").focus();
		<% else %>
			alert('Error creating category');
		<% end %>
	<% else %>
		try
		{
			str = " <tr id='r<%=@Category.id%>'> " + 
  			  	 " <td><input type='checkbox' id='c<%=@Category.id%>' value='<%=@Category.id%>' name='ps[]'/></td> " +
  			  	 " <td><%=@Category.name %></td> ";
			<% if @Category.categorytype.present? %>
				str += "<td><%=@Category.categorytype.name %></td> "; 
	  		<% else %>
				str += "<td>&nbsp;</td>";
	  		<% end %>
	  	    <% if @Category.parent.present? %>
				str += "<td><%=@Category.parent.name %></td>";
	  		<% else %>
				str += "<td>&nbsp;</td>";
	  		<% end %>
	  		<% if !@Category.created_at.nil?  %>
				str += "<td><%=@Category.created_at.strftime('%Y-%m-%d')%></td>";
	  		<% end %>
	  		<% if @Category.status.nil? %>
				str += "<td>Active</td>";
	  		<% else %>
	    		str += "<td>Inactive</td>";
	  		<% end %>
	  		str += "<td>";
  			str += "<%=escape_javascript(link_to(image_tag('delete.png',:border=>0), {:action=>'delete',:id=> @Category.id,:page=>@page},:method=>:post, :remote=>true, :data=> { :confirm=>'Are you sure?' })) %>";
  			str += "</td>";
 			str += "</tr>";
 			window.parent.updateData("edit",str,"r<%=@Category.id%>");
			window.parent.closeWindow("r<%=@Category.id%>");
  		}
  		catch(err)
  		{
  			alert("error" + err.message);
  		}
	<% end %>
<% rescue Exception => e %>
	alert("<%=e.message%>");
	<% puts "error in rescue"%>
	<% puts e.message %>
<% end %>

app/views/priority/index.js.erb
$('#categorytypes').html('<%=escape_javascript(render :partial => 'shared/categorytype')%>');
$('#page').val(<%=params[:page]%>);
$('.pagination a').attr('data-remote', 'true');